<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TRG_Markets.API</RootNamespace>
    <!-- Do not auto-generate package on every build to avoid packing transitive projects with invalid IDs -->
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>True</IncludeSymbols>
    <IsPackable>true</IsPackable>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controllers\TradesController . cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Controllers\TradesController . cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />

  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\TRG-Markets.Application\TRG-Markets.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TRG-Markets . Infrastructure\TRG-Markets . Infrastructure.csproj" />
  </ItemGroup>

</Project>
